### ISSUE TITLE
 android.app.ServiceConnectionLeaked

### ISSUE THREAD

**Issue by Lamba92** [okta/okta-sdk-appauth-android#9]
Something red appears on my logcat when launching this:
```
val completionIntent = Intent(this@LoginActivity, MainActivity::class.java)
            val cancelIntent = Intent(this@LoginActivity, LoginActivity::class.java)
            cancelIntent.flags = Intent.FLAG_ACTIVITY_CLEAR_TOP

            mOktaAuth.login(this@LoginActivity,
                    PendingIntent.getActivity(this@LoginActivity, OKTA_REQUEST_CODE, completionIntent, 0),
                    PendingIntent.getActivity(this@LoginActivity, OKTA_REQUEST_CODE, cancelIntent, 0)
```
Error:
```
02-20 17:08:47.153 7647-7647/it.projector.lamba.projector E/ActivityThread: Activity it.projector.lamba.projector.activities.LoginActivity has leaked ServiceConnection net.openid.appauth.browser.CustomTabManager$1@8c5b0a that was originally bound here
                                                                            android.app.ServiceConnectionLeaked: Activity it.projector.lamba.projector.activities.LoginActivity has leaked ServiceConnection net.openid.appauth.browser.CustomTabManager$1@8c5b0a that was originally bound here
                                                                                at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1532)
                                                                                at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1424)
                                                                                at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1605)
                                                                                at android.app.ContextImpl.bindService(ContextImpl.java:1557)
                                                                                at android.content.ContextWrapper.bindService(ContextWrapper.java:684)
                                                                                at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:70)
                                                                                at net.openid.appauth.browser.CustomTabManager.bind(CustomTabManager.java:95)
                                                                                at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:113)
                                                                                at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:91)
                                                                                at com.okta.appauth.android.OktaAppAuth.createAuthorizationService(OktaAppAuth.java:549)
                                                                                at com.okta.appauth.android.OktaAppAuth.recreateAuthorizationService(OktaAppAuth.java:540)
                                                                                at com.okta.appauth.android.OktaAppAuth.doInit(OktaAppAuth.java:430)
                                                                                at com.okta.appauth.android.OktaAppAuth.access$000(OktaAppAuth.java:69)
                                                                                at com.okta.appauth.android.OktaAppAuth$1.run(OktaAppAuth.java:157)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                at java.lang.Thread.run(Thread.java:764)
02-20 17:08:49.743 7647-7714/it.projector.lamba.projector D/BackendService: Current user JSON is:
                                                                            {"id":"00udnlrh5hxq6bLEJ0h7","externalId":null,"created":"2018-02-07T16:17:57.000Z","lastUpdated":"2018-02-10T00:33:16.000Z","scope":"GROUP","status":"ACTIVE","statusChanged":"2018-02-07T16:17:57.000Z","passwordChanged":null,"syncState":"DISABLED","credentials":{"userName":"basti.lamberto@gmail.com"},"profile":{"street_address":null,"country":null,"website":null,"zoneinfo":"America/Los_Angeles","birthdate":null,"gender":null,"formatted":null,"profile":null,"locality":null,"given_name":"Lamberto","middle_name":null,"locale":"en-US","picture":null,"bagde_number":"123456","name":"Lamberto Basti","nickname":null,"phone_number":null,"region":null,"postal_code":null,"family_name":"Basti","projectId":null,"email":"basti.lamberto@gmail.com"},"_links":{"app":{"href":"https://dev-928137.oktapreview.com/api/v1/apps/0oadx8g38e3bAet2I0h7"},"user":{"href":"https://dev-928137.oktapreview.com/api/v1/users/00udnlrh5hxq6bLEJ0h7"},"group":{"name":"Projector users","href":"https://dev-928137.oktapreview.com/api/v1/groups/00gdxb07rj5XzEMEM0h7"}}}

```

**Comment by jmelberg-okta** [comment]
Hey @Lamba92! Thanks for raising this issue.

Seems like it might be related to [this issue with AppAuth](https://github.com/openid/AppAuth-Android/issues/91).

I'll try and take a deeper look into this next week to see if we're not handling a case properly.
